version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/mobsec_db
      - REDIS_URL=redis://redis:6379
      - MODULES_PATH=/app/modules
      - EXTERNAL_MODULES_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./modules:/app/modules
      - shared_data:/shared_data
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mobsec_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    name: mobsec_app_network

volumes:
  pgdata:
    name: mobsec_pgdata
  shared_data:
    name: mobsec_shared_data