name: jadx_module
version: 0.1
description: Decompiles APK files using JADX
author: stormtrooperroman
requires_docker: true
mount_points:
  - source: shared_data
    target: /shared_data
environment:
  - JAVA_OPTS=-Xmx2g
