name: mitmproxy_module
version: 0.1
description: Dynamic instrumentation with Mitmproxy
author: Stormtrooperroman
active: True
type: dynamic
port: 8091
map_name: mitmproxy
view:
  icon: network-wired
  title: Traffic Monitor