name: permission_module
version: 0.1
description: Analyzes app permissions, components, and identifies dangerous permissions.
author: stormtrooperroman
requires_docker: true
mount_points:
  - source: shared_data
    target: /shared_data